### ISSUE TITLE
cinder-config.cmake

### ISSUE THREAD

**Issue by jalowin** [PetrosKataras/Cinder-NDI#1]
Hello:

I am trying compile this but I received this error

-- CINDER BLOCKS: Cinder-NDI
CMake Error at /home/administrador/Descargas/cinder_linux/proj/cmake/modules/cinderMakeApp.cmake:51 (find_package):
  Could not find a package configuration file provided by "cinder" with any
  of the following names:

```
cinderConfig.cmake
cinder-config.cmake
```

  Add the installation prefix of "cinder" to CMAKE_PREFIX_PATH or set
  "cinder_DIR" to a directory containing one of the above files.  If "cinder"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:11 (ci_make_app)

-- Configuring incomplete, errors occurred!
See also "/home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/samples/BasicSender/proj/cmake/build/CMakeFiles/CMakeOutput.log".

Can you say me wich are the error

I am using de cinder android_linux and set the ndi_sdk_path and this is the command to cmake
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/home
/administrador/Descargas/cinder_linux/lib/linux/x86_64

Thanks for all

best regards

**Comment by PetrosKataras** [comment]
Hi, 

have you actually build a Release version of Cinder? In any case this should work if you have all dependencies installed :

`cd /home/administrador/Descargas/cinder_linux && mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release && make -j4` . This will build a release version of Cinder.

Then to build the block :  
`cd /home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/samples/BasicSender/proj/cmake && mkdir build && cd build && export NDI_SDK_PATH=/path/to/NDI && cmake .. -DCMAKE_BUILD_TYPE=Release && make -j2`

Cheers,
Petros

**Comment by jalowin** [comment]
Ok, now cmake is ok but when i make -j2 i received this error

Scanning dependencies of target Cinder-NDI
[ 40%] Building CXX object CMakeFiles/Cinder-NDI.dir/home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/src/CinderNDIReceiver.cpp.o
[ 40%] Building CXX object CMakeFiles/Cinder-NDI.dir/home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/src/CinderNDISender.cpp.o
/home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/src/CinderNDISender.cpp: In member function ‘void CinderNDISender::sendSurface(cinder::SurfaceRef)’:
/home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/src/CinderNDISender.cpp:58:4: warning: narrowing conversion of ‘(unsigned int)surface.std::shared_ptr<cinder::SurfaceT<unsigned char> >::<anonymous>.std::__shared_ptr<_Tp, _Lp>::operator-><cinder::SurfaceT<unsigned char>, (__gnu_cxx::_Lock_policy)2u>()->cinder::SurfaceT<T>::getWidth<unsigned char>()’ from ‘unsigned int’ to ‘int’ inside { } [-Wnarrowing]
    };
    ^
/home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/src/CinderNDISender.cpp:58:4: warning: narrowing conversion of ‘(unsigned int)surface.std::shared_ptr<cinder::SurfaceT<unsigned char> >::<anonymous>.std::__shared_ptr<_Tp, _Lp>::operator-><cinder::SurfaceT<unsigned char>, (__gnu_cxx::_Lock_policy)2u>()->cinder::SurfaceT<T>::getHeight<unsigned char>()’ from ‘unsigned int’ to ‘int’ inside { } [-Wnarrowing]
/home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/src/CinderNDISender.cpp:58:4: error: cannot convert ‘bool’ to ‘NDIlib_frame_format_type_e’ in initialization
/home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/src/CinderNDISender.cpp:58:4: warning: narrowing conversion of ‘(unsigned int)surface.std::shared_ptr<cinder::SurfaceT<unsigned char> >::<anonymous>.std::__shared_ptr<_Tp, _Lp>::operator-><cinder::SurfaceT<unsigned char>, (__gnu_cxx::_Lock_policy)2u>()->cinder::SurfaceT<T>::getRowBytes<unsigned char>()’ from ‘unsigned int’ to ‘int’ inside { } [-Wnarrowing]
/home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/src/CinderNDIReceiver.cpp: In member function ‘void CinderNDIReceiver::setup()’:
/home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/src/CinderNDIReceiver.cpp:47:74: error: invalid conversion from ‘unsigned int_’ to ‘int_’ [-fpermissive]
    mNdiSources = NDIlib_find_get_sources( mNdiFinder, &no_sources, 10000 );
                                                                          ^
In file included from /home/administrador/Descargas/NDI_SDK_shared/include/Processing.NDI.Lib.h:72:0,
                 from /home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/include/CinderNDIReceiver.h:4,
                 from /home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/src/CinderNDIReceiver.cpp:1:
/home/administrador/Descargas/NDI_SDK_shared/include/Processing.NDI.Find.h:48:24: note:   initializing argument 2 of ‘const NDIlib_source_t\* NDIlib_find_get_sources(NDIlib_find_instance_t, int_, uint32_t)’
 const NDIlib_source_t_ NDIlib_find_get_sources(NDIlib_find_instance_t p_instanc
                        ^
/home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/src/CinderNDIReceiver.cpp: In member function ‘void CinderNDIReceiver::initConnection()’:
/home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/src/CinderNDIReceiver.cpp:63:3: error: cannot convert ‘bool’ to ‘NDIlib_recv_color_format_e’ in initialization
   };
   ^
/home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/src/CinderNDIReceiver.cpp: In member function ‘void CinderNDIReceiver::update()’:
/home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/src/CinderNDIReceiver.cpp:82:68: error: invalid conversion from ‘unsigned int_’ to ‘int_’ [-fpermissive]
  mNdiSources = NDIlib_find_get_sources( mNdiFinder, &no_sources, 0 );
                                                                    ^
In file included from /home/administrador/Descargas/NDI_SDK_shared/include/Processing.NDI.Lib.h:72:0,
                 from /home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/include/CinderNDIReceiver.h:4,
                 from /home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/src/CinderNDIReceiver.cpp:1:
/home/administrador/Descargas/NDI_SDK_shared/include/Processing.NDI.Find.h:48:24: note:   initializing argument 2 of ‘const NDIlib_source_t\* NDIlib_find_get_sources(NDIlib_find_instance_t, int_, uint32_t)’
 const NDIlib_source_t_ NDIlib_find_get_sources(NDIlib_find_instance_t p_instanc
                        ^
/home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/src/CinderNDIReceiver.cpp:88:74: error: invalid conversion from ‘unsigned int_’ to ‘int_’ [-fpermissive]
    mNdiSources = NDIlib_find_get_sources( mNdiFinder, &no_sources, 10000 );
                                                                          ^
In file included from /home/administrador/Descargas/NDI_SDK_shared/include/Processing.NDI.Lib.h:72:0,
                 from /home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/include/CinderNDIReceiver.h:4,
                 from /home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/src/CinderNDIReceiver.cpp:1:
/home/administrador/Descargas/NDI_SDK_shared/include/Processing.NDI.Find.h:48:24: note:   initializing argument 2 of ‘const NDIlib_source_t\* NDIlib_find_get_sources(NDIlib_find_instance_t, int_, uint32_t)’
 const NDIlib_source_t_ NDIlib_find_get_sources(NDIlib_find_instance_t p_instanc
                        ^
CMakeFiles/Cinder-NDI.dir/build.make:86: fallo en las instrucciones para el objetivo 'CMakeFiles/Cinder-NDI.dir/home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/src/CinderNDISender.cpp.o'
make[2]: **\* [CMakeFiles/Cinder-NDI.dir/home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/src/CinderNDISender.cpp.o] Error 1
make[2]: **\* Se espera a que terminen otras tareas....
CMakeFiles/Cinder-NDI.dir/build.make:62: fallo en las instrucciones para el objetivo 'CMakeFiles/Cinder-NDI.dir/home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/src/CinderNDIReceiver.cpp.o'
make[2]: **\* [CMakeFiles/Cinder-NDI.dir/home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/src/CinderNDIReceiver.cpp.o] Error 1
CMakeFiles/Makefile2:67: fallo en las instrucciones para el objetivo 'CMakeFiles/Cinder-NDI.dir/all'
make[1]: **\* [CMakeFiles/Cinder-NDI.dir/all] Error 2
Makefile:83: fallo en las instrucciones para el objetivo 'all'
make: **\* [all] Error 2

Thanks for all

Best regards

**Comment by PetrosKataras** [comment]
Which version of Linux and compiler are you using ?

**Comment by jalowin** [comment]
Ubuntu 16.04 x86_64 and cmake 3.5.1

**Comment by PetrosKataras** [comment]
I tested this with Xubuntu 16.04 which should not make a difference. The only thing I can think of is that the NDI SDK interface slightly changed - Did you downloaded it recently? In any case you can try to change [this line](https://github.com/PetrosKataras/Cinder-NDI/blob/master/src/CinderNDIReceiver.cpp#L44) to `int` instead of `unsigned int` and see if this helps..

**Comment by PetrosKataras** [comment]
You would also need to change it [https://github.com/PetrosKataras/Cinder-NDI/blob/master/src/CinderNDIReceiver.cpp#L80](here) and anywhere else that it requires an unsigned int.

**Comment by PetrosKataras** [comment]
Looking at it it really seems that you are using a different NDI SDK version. When did you download the one you are using??

**Comment by jalowin** [comment]
I am download the latest version of sdk

**Comment by PetrosKataras** [comment]
Try with the latest version of the SDK without making any changes to the block and see if that helps.

**Comment by jalowin** [comment]
I change the unsigned for int and I receive this

make[2]: se sale del directorio '/home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/samples/BasicRcv/proj/cmake/build'
make -f CMakeFiles/Cinder-NDI.dir/build.make CMakeFiles/Cinder-NDI.dir/build
make[2]: se entra en el directorio '/home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/samples/BasicRcv/proj/cmake/build'
[ 40%] Building CXX object CMakeFiles/Cinder-NDI.dir/home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/src/CinderNDIReceiver.cpp.o
[ 40%] Building CXX object CMakeFiles/Cinder-NDI.dir/home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/src/CinderNDISender.cpp.o
/usr/bin/c++   -DFT2_BUILD_LIBRARY -DFT_DEBUG_LEVEL_TRACE -D_GLFW_X11 -D_GLFW_GLX -D_GLFW_USE_OPENGL -D_GLIBCXX_USE_CXX11_ABI=0 -D_UNIX -I/home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/include -I/home/administrador/Descargas/NDI_SDK_for_Linux/include -isystem /home/administrador/Descargas/cinder_linux/include  -O3 -DNDEBUG   -std=c++11 -std=c++14 -o CMakeFiles/Cinder-NDI.dir/home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/src/CinderNDIReceiver.cpp.o -c /home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/src/CinderNDIReceiver.cpp
/usr/bin/c++   -DFT2_BUILD_LIBRARY -DFT_DEBUG_LEVEL_TRACE -D_GLFW_X11 -D_GLFW_GLX -D_GLFW_USE_OPENGL -D_GLIBCXX_USE_CXX11_ABI=0 -D_UNIX -I/home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/include -I/home/administrador/Descargas/NDI_SDK_for_Linux/include -isystem /home/administrador/Descargas/cinder_linux/include  -O3 -DNDEBUG   -std=c++11 -std=c++14 -o CMakeFiles/Cinder-NDI.dir/home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/src/CinderNDISender.cpp.o -c /home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/src/CinderNDISender.cpp
/home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/src/CinderNDISender.cpp: In member function ‘void CinderNDISender::sendSurface(cinder::SurfaceRef)’:
/home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/src/CinderNDISender.cpp:58:4: error: too many initializers for ‘const NDIlib_video_frame_t’
    };
    ^
/home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/src/CinderNDISender.cpp:58:4: error: invalid conversion from ‘long int’ to ‘BYTE\* {aka unsigned char_}’ [-fpermissive]
/home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/src/CinderNDISender.cpp:56:21: error: invalid conversion from ‘unsigned char_’ to ‘DWORD {aka unsigned int}’ [-fpermissive]
     surface->getData(),
                     ^
/home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/src/CinderNDIReceiver.cpp: In member function ‘void CinderNDIReceiver::setup()’:
/home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/src/CinderNDIReceiver.cpp:47:74: error: invalid conversion from ‘int_’ to ‘DWORD_ {aka unsigned int_}’ [-fpermissive]
    mNdiSources = NDIlib_find_get_sources( mNdiFinder, &no_sources, 10000 );
                                                                          ^
In file included from /home/administrador/Descargas/NDI_SDK_for_Linux/include/Processing.NDI.Lib.h:68:0,
                 from /home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/include/CinderNDIReceiver.h:4,
                 from /home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/src/CinderNDIReceiver.cpp:1:
/home/administrador/Descargas/NDI_SDK_for_Linux/include/Processing.NDI.Find.h:34:24: note:   initializing argument 2 of ‘const NDIlib_source_t_ NDIlib_find_get_sources(NDIlib_find_instance_t, DWORD_, DWORD)’
 const NDIlib_source_t_ NDIlib_find_get_sources(NDIlib_find_instance_t p_instanc
                        ^
/home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/src/CinderNDIReceiver.cpp: In member function ‘void CinderNDIReceiver::update()’:
/home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/src/CinderNDIReceiver.cpp:82:68: error: invalid conversion from ‘int_’ to ‘DWORD_ {aka unsigned int_}’ [-fpermissive]
  mNdiSources = NDIlib_find_get_sources( mNdiFinder, &no_sources, 0 );
                                                                    ^
In file included from /home/administrador/Descargas/NDI_SDK_for_Linux/include/Processing.NDI.Lib.h:68:0,
                 from /home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/include/CinderNDIReceiver.h:4,
                 from /home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/src/CinderNDIReceiver.cpp:1:
/home/administrador/Descargas/NDI_SDK_for_Linux/include/Processing.NDI.Find.h:34:24: note:   initializing argument 2 of ‘const NDIlib_source_t_ NDIlib_find_get_sources(NDIlib_find_instance_t, DWORD_, DWORD)’
 const NDIlib_source_t_ NDIlib_find_get_sources(NDIlib_find_instance_t p_instanc
                        ^
/home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/src/CinderNDIReceiver.cpp:88:74: error: invalid conversion from ‘int_’ to ‘DWORD_ {aka unsigned int_}’ [-fpermissive]
    mNdiSources = NDIlib_find_get_sources( mNdiFinder, &no_sources, 10000 );
                                                                          ^
In file included from /home/administrador/Descargas/NDI_SDK_for_Linux/include/Processing.NDI.Lib.h:68:0,
                 from /home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/include/CinderNDIReceiver.h:4,
                 from /home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/src/CinderNDIReceiver.cpp:1:
/home/administrador/Descargas/NDI_SDK_for_Linux/include/Processing.NDI.Find.h:34:24: note:   initializing argument 2 of ‘const NDIlib_source_t_ NDIlib_find_get_sources(NDIlib_find_instance_t, DWORD_, DWORD)’
 const NDIlib_source_t_ NDIlib_find_get_sources(NDIlib_find_instance_t p_instanc
                        ^
CMakeFiles/Cinder-NDI.dir/build.make:89: fallo en las instrucciones para el objetivo 'CMakeFiles/Cinder-NDI.dir/home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/src/CinderNDISender.cpp.o'
make[2]: **\* [CMakeFiles/Cinder-NDI.dir/home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/src/CinderNDISender.cpp.o] Error 1
make[2]: **\* Se espera a que terminen otras tareas....
CMakeFiles/Cinder-NDI.dir/build.make:65: fallo en las instrucciones para el objetivo 'CMakeFiles/Cinder-NDI.dir/home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/src/CinderNDIReceiver.cpp.o'
make[2]: **\* [CMakeFiles/Cinder-NDI.dir/home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/src/CinderNDIReceiver.cpp.o] Error 1
make[2]: se sale del directorio '/home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/samples/BasicRcv/proj/cmake/build'
CMakeFiles/Makefile2:70: fallo en las instrucciones para el objetivo 'CMakeFiles/Cinder-NDI.dir/all'
make[1]: **\* [CMakeFiles/Cinder-NDI.dir/all] Error 2
make[1]: se sale del directorio '/home/administrador/Descargas/cinder_linux/blocks/Cinder-NDI/samples/BasicRcv/proj/cmake/build'
Makefile:86: fallo en las instrucciones para el objetivo 'all'
make: **\* [all] Error

**Comment by jalowin** [comment]
The version of the sdk have been downloaded yesterday

**Comment by PetrosKataras** [comment]
Ok it might have been updated since I downloaded then which was around 10days ago.. I m not in front of the machine right now but I will check it later on properly and get back to you..

Cheers,
Petros

**Comment by jalowin** [comment]
ok, thanks for all

**Comment by PetrosKataras** [comment]
Hey, I just tried with a fresh download of the SDK and the block builds properly against it  ( on both OS X and Xubuntu 16.04 ) so I am not sure what is happening with your setup.

![screenshot_2016-10-18_16-56-59](https://cloud.githubusercontent.com/assets/1078053/19480769/ee980b22-954b-11e6-80a8-25ab1c98ed6c.png)

**Comment by jalowin** [comment]
This is the last ndi sdk?

**Comment by PetrosKataras** [comment]
I just re-downloaded but there are no changes either way since July. If you do an `ls -ltr` on the SDK dir what is the output ? ( it should be 7th July last modified.. )

**Comment by jalowin** [comment]
-rw-rw-r--  1 administrador administrador 1448764 may  4 17:30 NDI License Agreement.pdf
drwxrwxr-x  3 administrador administrador    4096 may 27 02:05 examples
drwxrwxr-x 10 administrador administrador    4096 jul  7 10:20 lib
drwxrwxr-x  2 administrador administrador    4096 jul  7 10:20 documentation
drwxrwxr-x 10 administrador administrador    4096 jul  7 10:20 bin
drwxrwxr-x  2 administrador administrador    4096 jul  7 10:20 logos
drwxrwxr-x  2 administrador administrador    4096 oct 17 15:28 include

**Comment by PetrosKataras** [comment]
Hmm ... Interesting your include dir is actually last modified yesterday...

**Comment by jalowin** [comment]
i have clone another the git from Cinder-NDI and compile the process and I obtain this

![captura de pantalla de 2016-10-18 16-12-49](https://cloud.githubusercontent.com/assets/749160/19481310/c2dc63f0-954d-11e6-8829-c49e89e726fb.png)

**Comment by jalowin** [comment]
ok, I unzip the file ndi sdk origial and the system is compile ok

Thanks for all

Best regards

**Comment by PetrosKataras** [comment]
I do not understand what exactly was the problem with your setup but in any case happy it worked for you in the end.
